version: "2"
services:
  app:
    container_name: app
    build: .
    #environment:
     # - MONGO_URI=mongodb://mongo:27017/projektnaNaloga
    ports:
      - "3001:3001"
    links:
      - mongo
  react:
    image: react_img
    build: .
    command: "npm start"
    ports:
      - "3000:3000"
    links:
      - "app"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"